### ISSUE TITLE
Not so much an issue, but rather a question

### ISSUE THREAD

**Issue by stusquared** [KitchenPC/core#6]
First off, thank you for open sourcing your code.
I am interested in using the NLP portion of the work to translate scraped ingredients into something a bit more meaningful. Is there an easy way to utilize just the NLP parsing portion of the Core library?

Thanks for your time!

**Comment by MikeChristensen** [comment]
Yea, should be pretty easy!  I'd read the Getting Started article:

https://blog.kitchenpc.com/2014/02/10/getting-started-with-kitchenpc/

You'll need to set up a context so that all the NLP data is loaded into memory.  After that, you can new up an `NLP.Parser` instance and call `Parse()` or `ParseAll()` to parse ingredient usage input.
